<script>

    // Basic Structure

    try {
        // Code that may throw an exception
    } catch (error) {
        // Handle the exception
    } finally {
        // Optional: Code that will always run
    }

    // 1. Basic Try-Catch Example
    try {
        throw "An error occurred";

    } catch (error) {
        console.log("Caught error:", error);
    }

    // 2 Handling Multiplr Exception

    try {
        let num = parseInt("ABC");
        if (isNaN(num)) {
            throw new Error("Invalid number format");
        }
    }
    catch (error) {
        console.log("Error: ", error.message);
    }

    // 3 uding finally block
    try {
        console.log("Executing try block");

    } catch (error) {
        console.log("Error caught");
    } finally {
        console.log("finally block Executed");
    }

    // 4 Division by zero exception
    function divide(a, b) {
        if (b === 0) {
            throw new Error("Division by zero is not allowed");
        }
        return a / b;
    }
    try {
        console.log(divide(10, 0));

    } catch (error) {
        console.log("Exception: ", error.message);
    }

    // 5. Try-Catch Inside a Function

    function riskyFunction() {
        try {
            throw new Error("Something went wrong");
        } catch (error) {
            console.log("Caught an error in function:", error.message);
        }
    }

    riskyFunction();
</script>